language: c
before_script:
- git clone "https://github.com/ZIM555/android_prebuilts_gcc.git" "$HOME/android_prebuilt_toolchains"
deploy:
  skip_cleanup: true
script:
- export ARCH=arm
- export CROSS_COMPILE="$HOME/android_prebuilt_toolchains/arm-eabi-4.7/bin/arm-eabi-"
- make -j4 delos_defconfig
- make -j4 
- git clone https://github.com/garbage-bin/BUILDS_OUTPUTS.git $HOME/kernel
- mv arch/arm/boot/zImage $HOME/kernel/zImage-$(date +%Y%m%d)
- cd $HOME/kernel
- git config --global user.email "androidlover5842@gmail.com"
- git config --global user.name "grace5921"
- git add .
- git commit -m "add build output" 
- git branch -m $(date +%Y%m%d)
- git push https://23abab2352a5be840a692642f3bdf46ab940fe68@github.com/garbage-bin/BUILDS_OUTPUTS $(date +%Y%m%d)
